import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import css from 'styled-jsx/css'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <p className='font-quicksand '>this is quicksand font testing</p>
        <p className='font-mulish '>this is muliu font testing</p>
      </div>

    </div>
  )
}

export default Home;
